### ISSUE TITLE
Variance over target is not calculated properly.

### ISSUE THREAD

**Issue by prasadcool** [okviz/CardWithStates#1]
Hi @danieleperilli ,
Thank you for sharing card with states project on GitHub. I have gone through your code and it is really a nice custom visual for Power BI. But the logic you have used for calculating variance over the target is ((value - target) / value ). I am trying to implement my logic in the source code as ((value - target) / target).
When I test my implemented logic in the developer mode of Power BI Pro service it gives me correct output of variance. But when I export the visual as package and import it in to the power bi desktop version it returns me calculated variance value according to ((value - target) / value ). 
Can you please suggest me any solution on this.?

1)Screenshot of Visual test on Power BI Pro Server
![screenshot 14](https://cloud.githubusercontent.com/assets/25797541/22982370/fdcaa5a0-f3c4-11e6-979b-9f2c7cceea2f.png)
2)Screenshot of Visual test on Power BI Desktop
![screenshot 15](https://cloud.githubusercontent.com/assets/25797541/22982371/fdcb8de4-f3c4-11e6-8d39-bae009429e25.png)

**Comment by danieleperilli** [comment]
It is a known issue and we will fix it very soon. 
You can’t simply recompile the visual  and use it because Power BI downgrade it to the version in gallery, sorry.
