### ISSUE TITLE
card with states - states 1,2,3  missing

### ISSUE THREAD

**Issue by asadr123** [okviz/CardWithStates#10]
I m using card with states v1.3.9... The states 1,2,3 for changing colour of data value have disappered in the format section. please see picture

![1](https://user-images.githubusercontent.com/38247879/38553277-46d03ffc-3cae-11e8-87f9-f0642982b08a.JPG)

**Comment by asadr123** [comment]
Has this been fixed ?

**Comment by danieleperilli** [comment]
I closed the issue because we released another version (v1.4.2) and we didn't receive a repro file from your side. So let's try the latest version, if the issue is on place, please send a report file to reproduce the issue.
