### ISSUE TITLE
Text not displaying

### ISSUE THREAD

**Issue by etienne-ld** [okviz/CardWithStates#11]
Since the past hours the visual is not displaying text.  It shows (Blank)
![image](https://user-images.githubusercontent.com/38252960/38560944-cd082436-3ca4-11e8-9480-d3b181863b77.png)
Display seems OK with int or decimal measure.  Only 

I use the visuals to change background and display message upon certain conditions.

When I first checked the "Format" Pane was not displaying the States options (exactly like previous submitted issue by other user) https://github.com/okviz/CardWithStates/issues/10

I updated  Visual to 1.4.1 but both issues remain.
Thanks

**Comment by etienne-ld** [comment]
I use this visual in various reports, only one report is showing the issue at the moment.  Thx

**Comment by theregal87** [comment]
I am also having this issue on all of my reports with this visual. All visuals are text and not int or decimal. Worked in version 1.3.9

**Comment by VitaliBurla** [comment]
Me too, I have a dashboard shared across the whole company and a few key indicators are visualized with the Cards. Now they don't work with text and default to blank. Using the very same measure with the standard built-in viz works. Please, look into this! Thank you very much for the effort in developing this visual.

**Comment by kleinrm2018** [comment]
Same issue with me. Online service shows all '(blank)' for all cards, however using desktop with older card version appears correctly. Assuming it's an issue with latest card version on online service of BI (since it's likely the latest updated version). No issues yesterday.

**Comment by spmion** [comment]
We're having the same issue in both the March 2018 and April 2018 Power BI Desktop versions. 1.4.1 was working with text in Power BI Desktop versions February 2018 and prior.

**Comment by DanWTET** [comment]
Same issue here - we use this visual with both numbers and text.
Text simply shows (BLANK), whilst numerical data seems to work fine.

**Comment by etienne-ld** [comment]
Hi @danieleperilli, any updates on this?  Some visuals were still OK 2 days ago until now, the problem seems to spread to more and more visuals now.  Thanks for your help!

**Comment by kleinrm2018** [comment]
Please advise. Awaiting any sort of development here.

**Comment by kleinrm2018** [comment]
In online version, card with states just says blank. Same report on desktop does NOT say blank.  Same report.

Desktop version:
![capture desktop](https://user-images.githubusercontent.com/38291172/38693844-a84a1b02-3e77-11e8-8a5f-4b32bbda586e.PNG)

Online Version:
![capture online](https://user-images.githubusercontent.com/38291172/38693850-ac5615ac-3e77-11e8-8555-d7b04e1c1b2d.PNG)

Assuming the online version has the latest (4.1) version of the visual as opposed to the desktop version, which is older as I've not updated it. Indicates a likely issue with latest version. If you need more than this obvious display of the issue, please let me know.

**Comment by danieleperilli** [comment]
Please send a sample PBIX report to support@okviz.com.

**Comment by marcosqlbi** [comment]
For those having a problem with card with states displaying a measure that returns a string: it seems that Microsoft is upgrading the component on powerbi.com with a new version (1.4.1). The bug seems to be present in 1.4.0 and 1.4.1 of Card with States. You can downgrade to 1.3.9 by downloading the version from https://okviz.com/card-with-states/ (click on older version and choose 1.3.9-beta). Please note that installing a beta you will lose the automatic upgrade from Microsoft, so you might also consider to wait a few days and check whether Microsoft solves the problem on powerbi.com (we already notified them the problem).

**Comment by spmion** [comment]
@danieleperilli I've sent a PBIX-based Repro exhibiting the behavior described in this thread to support@okviz.com.

**Comment by marcosqlbi** [comment]
Microsoft should revert to version 1.3.9 in a few hours - the reports using Card with States displaying measures returning strings should work soon.

**Comment by marcosqlbi** [comment]
The version 1.3.9 has been restored by Microsoft. You might have to clear the browser cache in case you still experience the problem.

**Comment by kleinrm2018** [comment]
Thank you for the notification. All looks good today.


[ABB logo]


—
Ryan Klein
Product Owner

ABB Enterprise Software
320 Interlocken Parkway
Broomfield, CO  80020
Phone: +1 (720) 240-5506
abb.com

**Comment by etienne-ld** [comment]
All good!
Thanks for follow-up!
