### ISSUE TITLE
Card With States Performance

### ISSUE THREAD

**Issue by mikumagic** [okviz/CardWithStates#12]
Hi,

For a while now, I have been struggling with published reports which contain multiple Cards With States.  I use single tiles showing a number in RED/YELLOW/GREEN depending on a target value.
When you have a few, they take a long time to appear on the page and are always the last items to appear.  Is this something which is being addressed?
Thanks,
Michael

**Comment by tringuyenminhmh** [comment]
Got same situation with @mikumagic . it's slow and slower than built-in control like card.

**Comment by marcosqlbi** [comment]
How many controls do you have in a single page? There is a problem with custom visuals in general, they can consume memory and if the computer doesn't have much RAM they slow down the entire page. It's a problem of the sandbox where Microsoft runs third party custom visuals, they are aware of the problem and we cannot do much except waiting for a better sandbox library from Microsoft. However, maybe that you are experiencing a different issue if you have only 3-4 custom visuals in a single page.

**Comment by tringuyenminhmh** [comment]
Actually I have the dashboard with 25 tiles (5 column bar charts, **9 card with state** and 11 cards) And same thing with report. When using cardwithstates, there is a little bit lagging. When rendering, it's always finish after another controls (one by one)  while built-in cards/charts show values immediately.

**Comment by mikumagic** [comment]
I agree with all of that – exactly the same issues.

I got around it by not using the cardswithstate and having to make mini tables with conditional formatting.  But I would love to use the single tiles again, when the performance improves.

**Comment by marcosqlbi** [comment]
9 cards is not a big number, performance might depend on CPU speed and RAM available of the PC running the browser.
Unfortunately, this is an issue shared by all of the custom visuals - we need a solution from Microsoft for that, because it depends on their library.

**Comment by johannkurz** [comment]
Have built a report page with 15 cards and it's very slow. Is there any update on the performance issue? Did you get support from Microsoft?
