### ISSUE TITLE
state-dependent formatting does not to work with a measure using the DAX FORMAT Command

### ISSUE THREAD

**Issue by bearnie** [okviz/CardWithStates#15]
First of all, thanks for publishing this very useful component. It saved my day when I was stuck with PBI's default card formatting options.
The issue is the following : state-dependent formatting does not to work with a measure using the DAX FORMAT Command.

The use case is that I need to display the percentage of confirmations that are sent within 24 hours of requests to measure a supplier's compliance to contractual terms.
To do so, I created the following custom measure :
```
confirmation_under_24hrs =
FORMAT((COUNTROWS(FILTER('Deals';'Deals'[confirmation_delay] < 24))/COUNTROWS('Deals'));"0%")
```
I needed to use the FORMAT command to display the "%" sign next to the value since you cannot display custom units in card in PBI.

Unfortunately, Card With States won't work when I use the FORMAT command in the custom measure.

To use state-related formatting, I had to create the same measure without the FORMAT command and use it as the States Measure :
```
confirmation_under_24hrs_value =
(COUNTROWS(FILTER('Deals';'Deals'[confirmation_delay] < 24))/COUNTROWS('Deals'))*100
```

This way the component works perfectly.

Thing is, you have to create two measures for the same information for the only sake of proper display.

Hope you can fix this somehow !

**Comment by danieleperilli** [comment]
You should use data modeling tab to format measures in Power BI instead of FORMAT formula.
