### ISSUE TITLE
States are not rendered correctly for negative numbers (only one state is evaluated)

### ISSUE THREAD

**Issue by jmheikkin** [okviz/CardWithStates#17]
I'm using the card with states visual (1.4.2.0) to visualize a percentage value and I'd like to color the font as green, yellow, or red based on the percentage value. This coloring works perfectly for positive percentage values, but with a negative value, the visual seems to only be able to handle the evaluation for the first state. Below is an example setup that wouldn't work. In this example setup the State A evaluation would remain effective (Yellow), even though the State B evaluation would pass also, meaning that the number is yellow when it should be green. Again, the same logic works perfectly with positive percentages, so I'm assuming this has something to do with the evaluation for negative numbers.

Measure value: -10.1%

**States config:**

Comparison:    >=
Base color:       Red
State A:            Yellow
State A value:   -0.12
State B:             Green
State B value:    -0.11

Unfortunately, I won't be able to share the pbix file, but since the issue setup would be so simple to reproduce, I was hoping you could still investigate if there's something to fix? I'm happy to provide other details if needed.

BR,
Joona

**Comment by danieleperilli** [comment]
As specified here (https://okviz.com/blog/states-in-custom-visuals/) the first state found determine the color.
