### ISSUE TITLE
Percentage Points

### ISSUE THREAD

**Issue by RussellLarkin** [okviz/CardWithStates#18]
Is there any chance of adding text on the variance line to include text before or after the value? Specifically, I would like to indicate on the visual that the variance is showing percentage points (pp) rather than percentage difference by adding "pp" to the end of the variance value.

**Comment by danieleperilli** [comment]
We collected your request, but we add new features according to users request and a priority list, so I don't know when and if it will be implemented.

**Comment by frankbilles** [comment]
We have the same issue, we want to indicate that we show percentage points (pp) in the variance.
Do you have an updated if this feature will be implemented ?
