### ISSUE TITLE
Data Label has no option for Aggregate

### ISSUE THREAD

**Issue by roabramson** [okviz/CardWithStates#20]
I have some measures that I really need to use the aggregate of in the data label value field and was disappointed to discover that's not an option.  Is there any way it can be added?

**Comment by danieleperilli** [comment]
The data label aggregation in the Properties pane in not reliable and precise as the same aggregation applied by Power BI from the context menu of the Fields pane. There is a technical reason for this and is related to the trendline.
I suggest you to use a separate Sparkline by OKViz for the trendline and to empty the trendline field in Card with States. This way you will be able to see all the standard aggregation options in the context menu of the main measure.
