### ISSUE TITLE
Category label shows twice when pin the card to dashboard

### ISSUE THREAD

**Issue by wujoho** [okviz/CardWithStates#22]
The default card from Microsoft only shows once at top left, but this custom visual shows both at top left and below.
![cardwithstates vs card from ms](https://user-images.githubusercontent.com/12386794/42612842-b7b88328-85f1-11e8-8640-55623605baab.png)

**Comment by danieleperilli** [comment]
We can't know if a custom visual is displayed in a Dashboard, so it is impossible to remove the data label automatically.
