### ISSUE TITLE
Problem with State and Target Fields

### ISSUE THREAD

**Issue by gabrielcmacedo** [okviz/CardWithStates#24]
Hello,

I have the following situation when using the "Card with states" component (version 1.4.2) of PowerBI (Version: 2.59.5135.421 64-bit (June 2018)) 

I created a measure whose value is 3 (I put it in the measure field) . I created an upper bound = 4 (I put in the state field ".LSPropostasApresentadas"), a lower limit = 0 (I put in the state field ". LIPropostasApresentadas ") and a target to be reached = 3 (I put in the target field ".MPropostasApresentadas"). Every information shown in the Picture "Target.PNG". In the configuration of the state (according to the pictures "States 1.PNG", "States 2.PNG" and "States 3.PNG") I define the colors and actions to be done, however, the component is not considering the information correctly (according to the Picture "Result.PNG", because by the validation logic, the component is validating the lower limit before the target. To fix this issue it should be possible to change the order of the validations in the state configuration.

Regards. 

![result](https://user-images.githubusercontent.com/42045731/43776690-fa1922ec-9a26-11e8-8293-a76e44da6688.PNG)
![states 1](https://user-images.githubusercontent.com/42045731/43776691-fa3c0b18-9a26-11e8-9fed-9c466b83daf2.PNG)
![states 2](https://user-images.githubusercontent.com/42045731/43776692-fa5e7518-9a26-11e8-877d-90b3efd8538e.PNG)
![states 3](https://user-images.githubusercontent.com/42045731/43776693-fa7f3532-9a26-11e8-8f24-7bd6fb1aaffe.PNG)
![target](https://user-images.githubusercontent.com/42045731/43776695-faab07fc-9a26-11e8-87e0-fbdae67bf15b.PNG)

**Comment by danieleperilli** [comment]
The base color is assigned only if there is no match with any state.
You set LISpropostasApresentadas = 0, so the state red is equal to 3.
