### ISSUE TITLE
Using visual with modern headers

### ISSUE THREAD

**Issue by dedelman04** [okviz/CardWithStates#25]
CardsWithStates v 1.4.2 (downloaded directly from marketplace)
PowerBI Desktop v 2.61.5192.601 64-bit (August 2018), modern headers enabled

Once I set up the visual, even with just a measure, the only way I can drag/move, copy or delete the visual is  to hover specifically over the small pop-up header then click and hold.  With built-in visuals, click and hold anywhere on the visual allows drag.

Also, cursor changes to "hand" when hovering over any part of the visual - changes back to arrow when hovering over the pop-up header.

When modern headers are not enabled, you must click-hold only in the header to move.

**Comment by danieleperilli** [comment]
Please, provide a repro file.

**Comment by dedelman04** [comment]
[repro.zip](https://github.com/okviz/CardWithStates/files/2368192/repro.zip)
Attached

**Comment by danieleperilli** [comment]
Sorry, we don't have any control on the feature. Perhaps it is not supported by custom visual yet, it is not documented. Anyway, the visual is draggable, so it is not a real issue.
