### ISSUE TITLE
Number values format 

### ISSUE THREAD

**Issue by douglasmk** [okviz/CardWithStates#3]
Hi, could you please fix the locale when formatting values?
I use "pt-BR" culture and numbers in Modeling tab of Power BI Desktop are in "pt-BR", but CardWithStates shows it in "en-us' format.

**Comment by okviz** [comment]
Unfortunately, it doesn't depend on us. The issue is related to the standard formatting library that we use in Card with States. We already reported the issue here: https://github.com/Microsoft/powerbi-visuals-utils-formattingutils/issues/17. Take a look and leave your voice!
