### ISSUE TITLE
New version update issue

### ISSUE THREAD

**Issue by jeeves1275** [okviz/CardWithStates#33]
Visual is not displaying - get an error message instead 
![2019-02-06_10-53-40](https://user-images.githubusercontent.com/47384659/52336976-43f3e480-29fe-11e9-8e31-46645225411a.png)
If I reimport the visual it does not update the existing visual, it adds it as a new one.  Means I would have to go through report and change all 48(!) visuals to point to the new one...please help! thanks

**Comment by okviz** [comment]
You are using an old version of the visual (more than 2 years old). You have to download the latest version from the Marketplace and manually update every report. Unfortunately, there isn't another way...

**Comment by jeeves1275** [comment]
OK, thanks will have to do that I guess.  Is there any way of predicting/being forewarned of this kind of update?  This has affected a Production report and will take some time to rectify, would be good to have some kind of warning beforehand.....cheers

**Comment by marcosqlbi** [comment]
The new components update automatically, unfortunately that old API didn't support the process - this depends on Microsoft, but now you should not have any issue. If you have other reports using components downloaded more than one year ago, I would suggest you to check whether they have the latest version from the marketplace.

**Comment by jeeves1275** [comment]
No worries, understood and thanks for the suggestion.
