### ISSUE TITLE
There was an issue loading one or more tiles

### ISSUE THREAD

**Issue by CathyNewport** [okviz/CardWithStates#37]
[Power bi issue Okviz.docx](https://github.com/okviz/CardWithStates/files/2905002/Power.bi.issue.Okviz.docx)

We already have Power Bi working with another program and I can't get the MYOB Accountright working. The power BI team have looked at the issue and recommended I contact Okviz support to help.

What do you suggest?

Below is the version of Power BI I am running via Chrome.
Power BI
©Microsoft Corporation 2019. All rights reserved.
Version13.0.8482.125
Activity ID9052c2bd-17a1-4f24-9cdd-c943d864bda9
TimeTue Feb 26 2019 21:45:57 GMT+1100 (Australian Eastern Daylight Time)
Your data is stored inAustralia Southeast (Victoria)
Tenant URL
https://app.powerbi.com/home?ctid=0174704a-ca68-4199-b41b-806c1968b089
****

**Comment by okviz** [comment]
You are using a very old version of the visual (more than 2 years old). You must update the visual by using the current version in the Marketplace.

**Comment by CathyNewport** [comment]
I have updated the visualization Card with States by OKViz with no resolution. I also have another named CardwithStateBySQLBI, would this be causing conflict?

**Comment by CathyNewport** [comment]
Thanks for your email. I have removed and reinstalled the app. I have logged out and in. Tried changing the visualisation. Was there anything else I can check?

I have only been using Power BI online for a few months and only just connected to the MYOB app yesterday so not sure why it would be out of date however now it still doesn't work.

Thanks,

Cathy


________________________________

**Comment by okviz** [comment]
You have to update all the visuals in your report. CardWithStatesBySQLBI is the old one.
It should work, if not, try to clear your cache.
