### ISSUE TITLE
States Measure has no effect in 1.3.7 Beta

### ISSUE THREAD

**Issue by mark-awhere** [okviz/CardWithStates#6]
States are no longer rendering based on States Measure while using 1.3.7 beta.  The state is rendering based off of Measure instead.  I've attached an example that shows the issue.  The background of the card should be green since the States Measure = 100.  However, the card is rendering a color based on the primary Measure instead.
[state-measure-issue.zip](https://github.com/okviz/CardWithStates/files/1318503/state-measure-issue.zip)

**Comment by okviz** [comment]
Thanks for reporting it! You're right, we just released a new version (v1.3.8) that should fix the issue.
