### ISSUE TITLE
Problem with "Nan" or "Infinity" value on card with states version 1.4.1 (BETA)

### ISSUE THREAD

**Issue by DWPronos** [okviz/CardWithStates#8]
Hello !
Im still have a "Nan" or "Infinity" value on the target.
On the target i tried use a ifferror function or just if(value=blank();0;value) but it is doesnt work on card with states version 1.4.1.  How i can fix it ?

**Comment by danieleperilli** [comment]
Please attach or send support@okviz.com a repro file.

**Comment by danieleperilli** [comment]
We released a new version. You can try it? We wasn't able to test your issue because you didn't sent any report file.
